### ISSUE TITLE
Edit fields overlap field labels

### ISSUE THREAD

**Issue by rob-smallshire** [sixty-north/bark-spider#22]
This screenshot is on Safari 9.0.1

![screen shot 2015-11-26 at 19 15 05](https://cloud.githubusercontent.com/assets/1044137/11429007/1f0ade50-9472-11e5-924a-59b07287729f.png)

**Comment by abingham** [comment]
Try the `parameter-layout` branch and see if that improves things. It might be best in the end to just always put the labels above the input, but for now I'm trying to keep the labels and controls on the same line (for the numeric inputs, at least).

**Comment by rob-smallshire** [comment]
Yes, Definitely better.

**Comment by abingham** [comment]
Fixed (at least, fixed enough) in 6577d80b1c9582fe1554b70e9c88e39207c5120b
